### **Foundations & Basic PyTorch Operations**

1. **Basic Tensor Creation:**
    
    *Question:* Write a PyTorch code snippet to create a 3×3 tensor of random numbers and multiply it by 2.
    
    *Why:* To ensure you understand tensor creation, basic arithmetic, and using built‑in functions.
    
2. **Tensor from Python Data Structures:**
    
    *Question:* How do you create a tensor from a list of lists and compute its element‑wise square?
    
    *Why:* It practices converting Python lists to tensors and applying element‑wise operations.
    
3. **Tensor Indexing & Slicing:**
    
    *Question:* Write code to slice a given 4×4 tensor to extract the middle 2×2 sub-tensor.
    
    *Why:* It reinforces your ability to index and manipulate tensor subsets.
    
4. **Broadcasting in PyTorch:**
    
    *Question:* Demonstrate broadcasting by adding a 1×3 tensor to a 4×3 tensor.
    
    *Why:* To understand how PyTorch automatically expands dimensions during operations.
    
5. **Matrix Multiplication:**
    
    *Question:* Write a snippet that computes the matrix product of two tensors using `torch.matmul`.
    
    *Why:* To become comfortable with linear algebra operations that are foundational in deep learning.
    
6. **Understanding Data Types:**
    
    *Question:* How do you change a tensor’s data type (e.g., from float32 to int64) and why might this be important?
    
    *Why:* It’s critical to know how data types affect model computations and performance.

In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


In [9]:
a=torch.rand(3,3)
a

tensor([[0.7306, 0.2937, 0.2449],
        [0.8485, 0.3236, 0.6789],
        [0.2295, 0.9020, 0.3697]])

In [10]:
a*2

tensor([[1.4612, 0.5875, 0.4897],
        [1.6970, 0.6471, 1.3578],
        [0.4590, 1.8040, 0.7394]])

In [11]:
b=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])**2
b

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [16]:
c = torch.arange(1, 17).reshape(4, 4)
display(c)
sub_tensor = c[1:3, 1:3]
display(sub_tensor)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

tensor([[ 6,  7],
        [10, 11]])

In [19]:
d=torch.ones(1,3)+torch.zeros(4,3)
d

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
torch.matmul(f,g)

tensor([[  8,  77],
        [ 20, 150]])

In [24]:
e=torch.tensor([1,2,3,4])
print(e.dtype)
e=e.type(torch.float32)
print(e.dtype)

torch.int64
torch.float32


### **Autograd & Custom Gradients**

1. **Gradient Computation Basics:**
    
    *Question:* Write a code snippet to compute the gradient of a simple scalar function (e.g., f(x)=x²) using `torch.autograd`.
    
    *Why:* To understand how PyTorch tracks operations and computes gradients automatically.
    
2. **Disabling Gradients:**
    
    *Question:* How would you disable gradient calculations during inference using PyTorch? Write an example.
    
    *Why:* This practice is essential for saving memory and speeding up inference.
    
3. **Custom Autograd Function:**
    
    *Question:* Create a custom PyTorch autograd Function for a simple operation (for example, a custom square function) that implements both forward and backward passes.
    
    *Why:* To deepen your understanding of the autograd system and custom gradient computation.
    
4. **In-place vs. Out-of-place Operations:**
    
    *Question:* Explain the difference between in-place and out-of-place tensor operations and demonstrate with a code example.
    
    *Why:* To learn how in-place operations can affect gradient tracking and memory usage.